pipeline {
    agent any

    tools {
        nodejs 'node18'
    }

    parameters {
        text(name: 'SCENARIO', defaultValue: 'Login test', description: 'Enter test scenario')
    }

    environment {
        OPENAI_API_KEY = credentials('openai-api-key')
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/Manu-Test28/Git_learns.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('ai-test-agentF') {
                    bat 'npm install'
                    bat 'npx playwright install'
                }
            }
        }

        stage('Generate Test (AI)') {
            steps {
                dir('ai-test-agentF') {
                    bat """
                    echo Scenario: %SCENARIO%
                    set SCENARIO=%SCENARIO%
                    npm run generate
                    """
                }
            }
        }

        stage('Run Playwright Tests') {
            steps {
                dir('ai-test-agentF') {
                    bat 'npm test'
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                dir('ai-test-agentF') {
                    bat 'npm run report'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'ai-test-agentF/allure-report/**', allowEmptyArchive: true
        }
    }
}
